### ISSUE TITLE
Uninitialized constant SpreeMultiDomain::Spree::Taxon

### ISSUE THREAD

**Issue by nolantait** [solidusio-contrib/solidus_multi_domain#124]
I'm getting a NameError: uninitialized constant SpreeMultiDomain::Spree::Taxon in app/decorators/controllers/spree_multi_domain/spree/taxons_controller_decorator.rb:5

https://github.com/solidusio-contrib/solidus_multi_domain/blob/acd8f68db606249464ba299020d19ebce7b11ae9/app/decorators/controllers/spree_multi_domain/spree/taxons_controller_decorator.rb#L5

Fix is simple to change:
`@taxon = ::Spree::Taxon.find_by_store_id_and_permalink!(current_store.id, params[:id])`

To:
`@taxon = Spree::Taxon.find_by_store_id_and_permalink!(current_store.id, params[:id])`

**Comment by hefan** [comment]
i got the same error message since the update 14c287f

https://github.com/solidusio-contrib/solidus_multi_domain/commit/14c287f18d6cbbd26ecddd5c8002039debfa2834#diff-545c76729c4b6e5c2be319f7f89257d5

it was wrong to replace
`@taxon = Spree::Taxon.find_by_store_id_and_permalink!(current_store.id, params[:id])`
with
`@taxon = Spree::Taxon.find_by!(store_id: current_store.id, permalink: params[:id])`

this is no coding style issue (although it looks like old style rails), but it actually is a class method defined here:
https://github.com/solidusio-contrib/solidus_multi_domain/blob/master/app/decorators/models/spree_multi_domain/spree/taxon_decorator.rb
store_id is no attribute of taxon, but of taxonomy.

in addition you need to ensure the correct namespace, so this here works:
`@taxon = ::Spree::Taxon.find_by_store_id_and_permalink!(current_store.id, params[:id])`

**Comment by hefan** [comment]
i've done a pull request
#126

**Comment by kennyadsl** [comment]
Thanks!
