### ISSUE TITLE
user manages single store

### ISSUE THREAD

**Issue by knagode** [solidusio-contrib/solidus_multi_domain#56]
Do you think that it would be hard to add role where user could manage single store?

I would like that added product would be visible just to his store, he would see only orders from his store, etc ... Or .. do you think it is better to write new admin for this purpose?

**Comment by adammathys** [comment]
It shouldn't be too hard to add the ability to scope stores to specific users. Some of the work required to make that happen was discussed in another PR: https://github.com/solidusio/solidus_multi_domain/pull/45

It would just be a matter of tweaking some of the permissions to allow a user to only access stores they're associated with as well as adding the table to associate users to stores. (Or if you're looking for a very quick and dirty approach, hard-coding the stores in the permissions associated to a role.)

In any case, there's basically two main components needed:

1. Associating users to stores. (Preferably a new join table, or could be hard-coded using a new role.)
2. Adding permission checks based on stores.

The second of which is like to be the more time-consuming task. Since there are a number of different views you'll want to ensure are correctly scoped.
