### ISSUE TITLE
Add taxons in taxonomy - engine.rb:41:in `find_layout_with_multi_store'

### ISSUE THREAD

**Issue by nigorice** [solidusio-contrib/solidus_multi_domain#63]
I'm trying to add new taxons but is encountering the following error:

GET "/api/taxonomies/1?set=nested"

```
Could not render layout: undefined method `compact' for nil:NilClass
/Users/nhamidjaja/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionview-5.0.1/lib/action_view/layouts.rb:412:in `rescue in _default_layout'
/Users/nhamidjaja/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionview-5.0.1/lib/action_view/layouts.rb:409:in `_default_layout'
/Users/nhamidjaja/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/actionview-5.0.1/lib/action_view/layouts.rb:386:in `block in _layout_for_option'
/Users/nhamidjaja/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/solidus_multi_domain-275db28ae094/lib/spree_multi_domain/engine.rb:41:in `find_layout_with_multi_store'
...
```

Using:

* solidus_multi_domain (2.0.0.alpha)
* solidus (2.1.0)

**Comment by kierr** [comment]
I have the same issue. Any solution?

**Comment by adammathys** [comment]
Unfortunately, there's no easy solution to this issue. It stems from the way this extension attempts to add in store specific layouts: https://github.com/solidusio/solidus_multi_domain/blob/master/lib/spree_multi_domain/engine.rb#L36-L55

Ideally, we would be using `prepend_view_path`. However, that means a significant change in  where we store layouts.

As a temporary workaround, assuming you aren't using the store specific layout feature, you can remove that specific monkey-patch.

**Comment by kierr** [comment]
Thanks so much for chiming in @adammathys. I am indeed making use of the store specific layout feature... for two different brand specific stores controlled by one master solidus instance. Perhaps then, using `prepend_view_path`, changing where layouts are stored would be my only solution? I'm not an incredibly advanced Ruby coder, but if I figure it out, I'll share my fork here. Any tips/suggestions welcome. Thanks again.

**Comment by adammathys** [comment]
@kierr It's likely to be your best solution. You'll want to remove the code in the extension responsible for monkey patching the layout rendering I linked above.

Then add in something along the lines of the following to your `ApplicationController`. (Or whatever base controller your front-end controllers inherit from.)
```ruby
before_action :prepend_current_store_path

def prepend_current_store_path
  prepend_view_path "app/views/#{current_store.code}"
end
```

Then you can place all of your layouts in `app/views/store_code/layouts/` instead of `app/views/layouts/store_code/`. This also has the added bonus of making it possible to override specific views if necessary. Which should make it a little easier to re-use partials across your different stores. Not to mention allowing Rails to default back to `app/views/layouts` should you not need to override the layout for a store.
