### ISSUE TITLE
Is there a way to get current_store outside of a controller?

### ISSUE THREAD

**Issue by kevinnio** [solidusio-contrib/solidus_multi_domain#82]
Hi, guys. Nice gem you have here. I was wondering if there's a way to access `current_store` outside of a Rails controller/view scope. I tried including `Spree::Core::ControllerHelpers::Store` but since `current_store` requires the `request` object it isn't obvious to me how to tackle this.

**Comment by adammathys** [comment]
As you've noted, `current_store` relies on `request`. This is because it only makes sense in the context of a web request. In order to determine the current store, we need knowledge about the request being made.

If you're looking to access a specific store in a model or a service object, you'll need to pass the store through from the controller. If appropriate, you can store it on the record directly. (e.g.: Like Solidus does with `Spree::Order`.)

**Comment by kevinnio** [comment]
I ended up adding a middleware which stores the request in a global variable so I can access it from the code which uses `current_store`. Not sure is this the ideal way to do it, but hey it works.
